<?php

namespace ContainerA0h7qeP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIASfbpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jIASfbp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jIASfbp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.jIASfbp.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.jIASfbp": it references class "App\\Entity\\Categorie" but no such service exists.'],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
