<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Praxg8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Praxg8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Praxg8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Praxg8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Praxg8\App_KernelDevDebugContainer([
    'container.build_hash' => '2Praxg8',
    'container.build_id' => '3cf27b34',
    'container.build_time' => 1647003005,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Praxg8');
